### ISSUE TITLE
Completion after -> doesn't work

### ISSUE THREAD

**Issue by dawiddr** [sphaerophoria/atom-rtags-plus#1]
Thank you for this useful plugin!

One issue I've noticed is that autocompletion doesn't work after `->` operator. I suspect it's related to a column number that gets passed to `rc`, because I get expected suggestions after I put a space after `->`.

For example:
`iterator->|` - no autocompletion suggestions
`iterator-> |` - suggestions expected for `->`
Where `|` is the position of the cursor.

**Comment by sphaerophoria** [comment]
Hm this seems to be a pretty strange case. With the . operator or the :: operators rtags gives us a list of completions. Workaround is to add a space when we're starting a new completion. I can't think of any cases where this will bite us, however I could be wrong.

This also brought my attention to some weird edge cases around handling of completions after :: which I have also resolved.

Thanks for the report.
