### ISSUE TITLE
atom-rtags-plus doesn't show up in github search

### ISSUE THREAD

**Issue by phord** [sphaerophoria/atom-rtags-plus#2]
If I go to github.com and search for atom-rtags-plus, github says:

> https://github.com/search?utf8=%E2%9C%93&q=atom-rtags-plus
>     We couldn’t find any repositories matching 'atom-rtags-plus'

To find the atom-rtags-plus project natively, I search for atom-rtags:

    https://github.com/search?utf8=%E2%9C%93&q=atom-rtags

It doesn't find this project.  It finds the original rajendrant project and another abandoned one:

-     rajendrant/atom-rtags
-     artagnon/atomic-rtags

To get to this project, then I have to open rajendrant's and then click the "fork-number" to finally get to this fork.

This isn't a problem with the code; it's some github oddity. But I suppose it's hard to notice when you own the repo.

**Comment by sphaerophoria** [comment]
Unfortunately this is a flaw with the github search. If you do https://github.com/search?utf8=%E2%9C%93&q=atom-rtags-plus+fork%3Atrue&type=Repositories&ref=searchresults then it seems to get it just fine.

Maybe use an external search engine and filter results from github.com for an easy way to find.
