### ISSUE TITLE
Add support for "open files" optimization (set-buffers)

### ISSUE THREAD

**Issue by phord** [sphaerophoria/atom-rtags-plus#3]
Rtags has a feature that lets you list which buffers you have open in the editor.  These buffers get pushed to the head of the queue when files are being indexed.  It's helpful on a project that takes 20 minutes to reindex to have my "interesting" files indexed first after I've changed a common header file rather than having to wait for everything to be reindexed.

The command is 

      rc --set-buffers "[file[;file[...]]]"

That is, the filenames all go in a single argument separated by semicolons.

You can query the current list with "rc --list-buffers".

There doesn't seem to be a way to append to the list.  I suppose whenever the editor has the focus it should list all its open buffers again.

**Comment by sphaerophoria** [comment]
Hm. I think we can do better than listing "all open buffers". I think we could subscribe to workspace.onDidChangeActivePaneItem and update it prioritizing the last focused buffer. 

Good find :).
