### ISSUE TITLE
Linting is broken

### ISSUE THREAD

**Issue by dawiddr** [sphaerophoria/atom-rtags-plus#6]
Linting doesn't work for me anymore (after package update?) I can see compilation errors in `rdm` output (even for unsaved changes), but none of them appear in Atom.

*My environment:*
Ubuntu Linux 16.04
atom-rtags-plus 1.4.0
linter 2.1.0
rtags 2.8

**Comment by sphaerophoria** [comment]
Probably the switch from linter 1->2. I haven't upgraded myself yet so haven't seen it. Thanks for the report.

**Comment by sphaerophoria** [comment]
Hm linting works fine for me. Keep in mind that it will only update it's status for the last few viewed files. Did you install all the new dependencies for linter?

That being said there are some bugs that need to be addressed in the Linter v2 api change so I'll have to address those.

**Comment by dawiddr** [comment]
Actually, I think that was broken even before I had updated Linter.

Output of Linter: Debug command looks suspicious:
```
Linter Debug Info
Platform: linux
Atom Version: 1.15.0
Linter Version: 2.1.0
All Linter Providers: 
Matching Linter Providers: 
Disabled Linter Providers; 
Current File scopes: 
  - *
  - source.cpp
  - meta.namespace-block.cpp
  - meta.class-struct-block.cpp
  - meta.function.constructor.initializer-list.cpp
  - meta.function.c
  - meta.block.c
  - punctuation.section.block.end.c
```

It would mean that no linters are registered, right? Following this lead, I've tried setting a breakpoint in `RtagsLinter.registerLinter`, but it seems to register itself in Linter just fine...

Here are my configs:
```
> JSON.stringify(atom.config.get("atom-rtags-plus"))
"{"rcCommand":"/home/drechny/local/bin/rc","rdmCommand":"","codeCompletion":true,"fuzzyCodeCompletion":true,"codeLinting":true,"keybindingStyle":3,"liveParsing":true,"liveParseFileTypes":["source.cpp","source.c"]}"
> JSON.stringify(atom.config.get("linter"))
"{"errorPanelHeight":135,"lintPreviewTabs":true,"lintOnOpen":true,"lintOnChange":true,"lintOnChangeInterval":300,"ignoreGlob":"**/*.min.{js,css}"}"
```

**Comment by schultzern** [comment]
The new linter package (v2.1.0) has moved the UI to _linter-ui-default_. Run "apm install linter-ui-default" to install it. (see http://steelbrain.me)

However I'm not sure if _atom-rtags-plus_ is compatible with v2.1.0 yet. I'm getting error messages that linter is not reciveing the right type. Has to be of type error/warning/info. 

Revert to _linter_ version 1.11.23 by "apm remove linter && apm install linter@1.11.23".  This fixes the issue for me. 

PS @sphaerophoria & @rajendrant: Thank you for developing _atom-rtags-plus_. Great package!!

**Comment by dawiddr** [comment]
I've already had *linter-ui-default* installed, but reverting *linter* to the old version has helped, so thank you for that suggestion.

**Comment by sphaerophoria** [comment]
Ive upgraded to the linter v2 api. Hopefully that resolves this.

**Comment by dawiddr** [comment]
I've just checked and now it works great with Linter v2!
